"use strict";(function(){var
userAgent=navigator.userAgent.toLowerCase(),initialDate=new Date(),$document=$(document),$window=$(window),$html=$("html"),$body=$("body"),isDesktop=$html.hasClass("desktop"),isIE=userAgent.indexOf("msie")!==-1?parseInt(userAgent.split("msie")[1],10):userAgent.indexOf("trident")!==-1?11:userAgent.indexOf("edge")!==-1?12:false,isMobile=/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),windowReady=false,isNoviBuilder=false,livedemo=true,plugins={bootstrapModal:$('.modal'),bootstrapTabs:$('.tabs-custom'),rdNavbar:$('.rd-navbar'),materialParallax:$('.parallax-container'),rdMailForm:$('.rd-mailform'),rdInputLabel:$('.form-label'),regula:$('[data-constraints]'),owl:$('.owl-carousel'),preloader:$('.preloader'),swiper:$('.swiper-slider'),search:$('.rd-search'),searchResults:$('.rd-search-results'),lightGallery:$("[data-lightgallery='group']"),lightGalleryItem:$("[data-lightgallery='item']"),lightDynamicGalleryItem:$("[data-lightgallery='dynamic']"),radio:$("input[type='radio']"),customToggle:$('[data-custom-toggle]'),wow:$('.wow'),maps:$('.google-map-container'),counter:$('.counter'),progressLinear:$('.progress-linear'),circleProgress:$('.progress-bar-circle'),rdAudioPlayer:$('.rd-audio'),slick:$('.slick-slider'),countDown:$('.countdown'),calendar:$('.rd-calendar'),bookingCalendar:$('.booking-calendar'),copyrightYear:$('.copyright-year')};function isScrolledIntoView(elem){if(isNoviBuilder)return true;return elem.offset().top+elem.outerHeight()>=$window.scrollTop()&&elem.offset().top<=$window.scrollTop()+$window.height();}
function lazyInit(element,func){var scrollHandler=function(){if((!element.hasClass('lazy-loaded')&&(isScrolledIntoView(element)))){func.call(element);element.addClass('lazy-loaded');}};scrollHandler();$window.on('scroll',scrollHandler);}
$window.on('load',function(){if(plugins.preloader.length&&!isNoviBuilder){pageTransition({target:document.querySelector('.page'),delay:0,duration:500,classIn:'fadeIn',classOut:'fadeOut',classActive:'animated',conditions:function(event,link){return link&&!/(\#|javascript:void\(0\)|callto:|tel:|mailto:|:\/\/)/.test(link)&&!event.currentTarget.hasAttribute('data-lightgallery');},onTransitionStart:function(options){setTimeout(function(){plugins.preloader.removeClass('loaded');},options.duration*.75);},onReady:function(){plugins.preloader.addClass('loaded');windowReady=true;}});}
if(plugins.counter.length){for(var i=0;i<plugins.counter.length;i++){var
counter=$(plugins.counter[i]),initCount=function(){var counter=$(this);if(!counter.hasClass("animated-first")&&isScrolledIntoView(counter)){counter.countTo({refreshInterval:40,speed:counter.attr("data-speed")||1000,from:0,to:parseInt(counter.text(),10)});counter.addClass('animated-first');}};$.proxy(initCount,counter)();$window.on("scroll",$.proxy(initCount,counter));}}
if(plugins.progressLinear.length){for(i=0;i<plugins.progressLinear.length;i++){var
progressBar=$(plugins.progressLinear[i]),initProgressLinear=function(){var bar=$(this);if(!bar.hasClass('animated-first')&&isScrolledIntoView(bar)){var end=parseInt($(this).find('.progress-value').text(),10);bar.find('.progress-bar-linear').css({width:end+'%'});bar.find('.progress-value').countTo({refreshInterval:40,from:0,to:end,speed:500});bar.addClass('animated-first');}};$.proxy(initProgressLinear,progressBar)();$window.on("scroll",$.proxy(initProgressLinear,progressBar));}}
if(plugins.materialParallax.length){if(!isNoviBuilder&&!isIE&&!isMobile){plugins.materialParallax.parallax();}else{for(var i=0;i<plugins.materialParallax.length;i++){var $parallax=$(plugins.materialParallax[i]);$parallax.addClass('parallax-disabled');$parallax.css({"background-image":'url('+$parallax.data("parallax-img")+')'});}}}});$(function(){isNoviBuilder=window.xMode;function toggleSwiperInnerVideos(swiper){var prevSlide=$(swiper.slides[swiper.previousIndex]),nextSlide=$(swiper.slides[swiper.activeIndex]),videos,videoItems=prevSlide.find("video");for(var i=0;i<videoItems.length;i++){videoItems[i].pause();}
videos=nextSlide.find("video");if(videos.length){videos.get(0).play();}}
function toggleSwiperCaptionAnimation(swiper){var prevSlide=$(swiper.container).find("[data-caption-animate]"),nextSlide=$(swiper.slides[swiper.activeIndex]).find("[data-caption-animate]"),delay,duration,nextSlideItem,prevSlideItem;for(var i=0;i<prevSlide.length;i++){prevSlideItem=$(prevSlide[i]);prevSlideItem.removeClass("animated").removeClass(prevSlideItem.attr("data-caption-animate")).addClass("not-animated");}
var tempFunction=function(nextSlideItem,duration){return function(){nextSlideItem.removeClass("not-animated").addClass(nextSlideItem.attr("data-caption-animate")).addClass("animated");if(duration){nextSlideItem.css('animation-duration',duration+'ms');}};};for(var i=0;i<nextSlide.length;i++){nextSlideItem=$(nextSlide[i]);delay=nextSlideItem.attr("data-caption-delay");duration=nextSlideItem.attr('data-caption-duration');if(!isNoviBuilder){if(delay){setTimeout(tempFunction(nextSlideItem,duration),parseInt(delay,10));}else{tempFunction(nextSlideItem,duration);}}else{nextSlideItem.removeClass("not-animated")}}}
function initOwlCarousel(carousel){var
aliaces=['-','-sm-','-md-','-lg-','-xl-','-xxl-'],values=[0,576,768,992,1200,1600],responsive={},resizeCb=function(){initLightGalleryItem(carousel.find('[data-lightgallery="item"]'),'lightGallery-in-carousel');};for(var j=0;j<values.length;j++){responsive[values[j]]={};for(var k=j;k>=-1;k--){if(!responsive[values[j]]['items']&&carousel.attr('data'+aliaces[k]+'items')){responsive[values[j]]['items']=k<0?1:parseInt(carousel.attr('data'+aliaces[k]+'items'),10);}
if(!responsive[values[j]]['stagePadding']&&responsive[values[j]]['stagePadding']!==0&&carousel.attr('data'+aliaces[k]+'stage-padding')){responsive[values[j]]['stagePadding']=k<0?0:parseInt(carousel.attr('data'+aliaces[k]+'stage-padding'),10);}
if(!responsive[values[j]]['margin']&&responsive[values[j]]['margin']!==0&&carousel.attr('data'+aliaces[k]+'margin')){responsive[values[j]]['margin']=k<0?30:parseInt(carousel.attr('data'+aliaces[k]+'margin'),10);}}}
if(carousel.attr('data-dots-custom')){carousel.on('initialized.owl.carousel',function(event){var
carousel=$(event.currentTarget),customPag=$(carousel.attr('data-dots-custom')),active=0;if(carousel.attr('data-active')){active=parseInt(carousel.attr('data-active'),10);}
carousel.trigger('to.owl.carousel',[active,300,true]);customPag.find('[data-owl-item="'+active+'"]').addClass('active');customPag.find('[data-owl-item]').on('click',function(event){event.preventDefault();carousel.trigger('to.owl.carousel',[parseInt(this.getAttribute('data-owl-item'),10),300,true]);});carousel.on('translate.owl.carousel',function(event){customPag.find('.active').removeClass('active');customPag.find('[data-owl-item="'+event.item.index+'"]').addClass('active')});});}
carousel.on('initialized.owl.carousel',resizeCb);carousel.on('resize.owl.carousel',resizeCb);carousel.owlCarousel({autoplay:isNoviBuilder?false:carousel.attr('data-autoplay')!=='false',autoplayTimeout:carousel.attr("data-autoplay")?Number(carousel.attr("data-autoplay")):3000,autoplayHoverPause:true,loop:isNoviBuilder?false:carousel.attr('data-loop')!=='false',items:1,center:carousel.attr('data-center')==='true',dotsContainer:carousel.attr('data-pagination-class')||false,navContainer:carousel.attr('data-navigation-class')||false,mouseDrag:isNoviBuilder?false:carousel.attr('data-mouse-drag')!=='false',nav:carousel.attr('data-nav')==='true',dots:carousel.attr('data-dots')==='true',dotsEach:carousel.attr('data-dots-each')?parseInt(carousel.attr('data-dots-each'),10):false,animateIn:carousel.attr('data-animation-in')?carousel.attr('data-animation-in'):false,animateOut:carousel.attr('data-animation-out')?carousel.attr('data-animation-out'):false,responsive:responsive,navText:carousel.attr('data-nav-text')?$.parseJSON(carousel.attr('data-nav-text')):[],navClass:carousel.attr('data-nav-class')?$.parseJSON(carousel.attr('data-nav-class')):['owl-prev','owl-next']});}
function liveSearch(options){$('#'+options.live).removeClass('cleared').html();options.current++;options.spin.addClass('loading');$.get(handler,{s:decodeURI(options.term),liveSearch:options.live,dataType:"html",liveCount:options.liveCount,filter:options.filter,template:options.template},function(data){options.processed++;var live=$('#'+options.live);if((options.processed===options.current)&&!live.hasClass('cleared')){live.find('> #search-results').removeClass('active');live.html(data);setTimeout(function(){live.find('> #search-results').addClass('active');},50);}
options.spin.parents('.rd-search').find('.input-group-addon').removeClass('loading');})}
function attachFormValidator(elements){regula.custom({name:'PhoneNumber',defaultMessage:'Invalid phone number format',validator:function(){if(this.value==='')return true;else return /^(\+\d)?[0-9\-\(\) ]{5,}$/i.test(this.value);}});for(var i=0;i<elements.length;i++){var o=$(elements[i]),v;o.addClass("form-control-has-validation").after("<span class='form-validation'></span>");v=o.parent().find(".form-validation");if(v.is(":last-child"))o.addClass("form-control-last-child");}
elements.on('input change propertychange blur',function(e){var $this=$(this),results;if(e.type!=="blur")if(!$this.parent().hasClass("has-error"))return;if($this.parents('.rd-mailform').hasClass('success'))return;if((results=$this.regula('validate')).length){for(i=0;i<results.length;i++){$this.siblings(".form-validation").text(results[i].message).parent().addClass("has-error");}}else{$this.siblings(".form-validation").text("").parent().removeClass("has-error")}}).regula('bind');var regularConstraintsMessages=[{type:regula.Constraint.Required,newMessage:"The text field is required."},{type:regula.Constraint.Email,newMessage:"The email is not a valid email."},{type:regula.Constraint.Numeric,newMessage:"Only numbers are required"},{type:regula.Constraint.Selected,newMessage:"Please choose an option."}];for(var i=0;i<regularConstraintsMessages.length;i++){var regularConstraint=regularConstraintsMessages[i];regula.override({constraintType:regularConstraint.type,defaultMessage:regularConstraint.newMessage});}}
function isValidated(elements,captcha){var results,errors=0;if(elements.length){for(var j=0;j<elements.length;j++){var $input=$(elements[j]);if((results=$input.regula('validate')).length){for(k=0;k<results.length;k++){errors++;$input.siblings(".form-validation").text(results[k].message).parent().addClass("has-error");}}else{$input.siblings(".form-validation").text("").parent().removeClass("has-error")}}
if(captcha){if(captcha.length){return validateReCaptcha(captcha)&&errors===0}}
return errors===0;}
return true;}
function initLightGallery(itemsToInit,addClass){if(!isNoviBuilder){$(itemsToInit).lightGallery({thumbnail:$(itemsToInit).attr("data-lg-thumbnail")!=="false",selector:"[data-lightgallery='item']",autoplay:$(itemsToInit).attr("data-lg-autoplay")==="true",pause:parseInt($(itemsToInit).attr("data-lg-autoplay-delay"))||5000,addClass:addClass,mode:$(itemsToInit).attr("data-lg-animation")||"lg-slide",loop:$(itemsToInit).attr("data-lg-loop")!=="false"});}}
function initDynamicLightGallery(itemsToInit,addClass){if(!isNoviBuilder){$(itemsToInit).on("click",function(){$(itemsToInit).lightGallery({thumbnail:$(itemsToInit).attr("data-lg-thumbnail")!=="false",selector:"[data-lightgallery='item']",autoplay:$(itemsToInit).attr("data-lg-autoplay")==="true",pause:parseInt($(itemsToInit).attr("data-lg-autoplay-delay"))||5000,addClass:addClass,mode:$(itemsToInit).attr("data-lg-animation")||"lg-slide",loop:$(itemsToInit).attr("data-lg-loop")!=="false",dynamic:true,dynamicEl:JSON.parse($(itemsToInit).attr("data-lg-dynamic-elements"))||[]});});}}
function initLightGalleryItem(itemToInit,addClass){if(!isNoviBuilder){$(itemToInit).lightGallery({selector:"this",addClass:addClass,counter:false,youtubePlayerParams:{modestbranding:1,showinfo:0,rel:0,controls:0},vimeoPlayerParams:{byline:0,portrait:0}});}}
function getLatLngObject(str,marker,map,callback){var coordinates={};try{coordinates=JSON.parse(str);callback(new google.maps.LatLng(coordinates.lat,coordinates.lng),marker,map)}catch(e){map.geocoder.geocode({'address':str},function(results,status){if(status===google.maps.GeocoderStatus.OK){var latitude=results[0].geometry.location.lat();var longitude=results[0].geometry.location.lng();callback(new google.maps.LatLng(parseFloat(latitude),parseFloat(longitude)),marker,map)}})}}
function initMaps(){var key;for(var i=0;i<plugins.maps.length;i++){if(plugins.maps[i].hasAttribute("data-key")){key=plugins.maps[i].getAttribute("data-key");break;}}
$.getScript('//maps.google.com/maps/api/js?'+(key?'key='+key+'&':'')+'sensor=false&libraries=geometry,places&v=quarterly',function(){var head=document.getElementsByTagName('head')[0],insertBefore=head.insertBefore;head.insertBefore=function(newElement,referenceElement){if(newElement.href&&newElement.href.indexOf('//fonts.googleapis.com/css?family=Roboto')!==-1||newElement.innerHTML.indexOf('gm-style')!==-1){return;}
insertBefore.call(head,newElement,referenceElement);};var geocoder=new google.maps.Geocoder;for(var i=0;i<plugins.maps.length;i++){var zoom=parseInt(plugins.maps[i].getAttribute("data-zoom"),10)||11;var styles=plugins.maps[i].hasAttribute('data-styles')?JSON.parse(plugins.maps[i].getAttribute("data-styles")):[];var center=plugins.maps[i].getAttribute("data-center")||"New York";var map=new google.maps.Map(plugins.maps[i].querySelectorAll(".google-map")[0],{zoom:zoom,styles:styles,scrollwheel:false,center:{lat:0,lng:0}});plugins.maps[i].map=map;plugins.maps[i].geocoder=geocoder;plugins.maps[i].keySupported=true;plugins.maps[i].google=google;getLatLngObject(center,null,plugins.maps[i],function(location,markerElement,mapElement){mapElement.map.setCenter(location);});var markerItems=plugins.maps[i].querySelectorAll(".google-map-markers li");if(markerItems.length){var markers=[];for(var j=0;j<markerItems.length;j++){var markerElement=markerItems[j];getLatLngObject(markerElement.getAttribute("data-location"),markerElement,plugins.maps[i],function(location,markerElement,mapElement){var icon=markerElement.getAttribute("data-icon")||mapElement.getAttribute("data-icon");var activeIcon=markerElement.getAttribute("data-icon-active")||mapElement.getAttribute("data-icon-active");var info=markerElement.getAttribute("data-description")||"";var infoWindow=new google.maps.InfoWindow({content:info});markerElement.infoWindow=infoWindow;var markerData={position:location,map:mapElement.map}
if(icon){markerData.icon=icon;}
var marker=new google.maps.Marker(markerData);markerElement.gmarker=marker;markers.push({markerElement:markerElement,infoWindow:infoWindow});marker.isActive=false;google.maps.event.addListener(infoWindow,'closeclick',(function(markerElement,mapElement){var markerIcon=null;markerElement.gmarker.isActive=false;markerIcon=markerElement.getAttribute("data-icon")||mapElement.getAttribute("data-icon");markerElement.gmarker.setIcon(markerIcon);}).bind(this,markerElement,mapElement));google.maps.event.addListener(marker,'click',(function(markerElement,mapElement){if(markerElement.infoWindow.getContent().length===0)return;var gMarker,currentMarker=markerElement.gmarker,currentInfoWindow;for(var k=0;k<markers.length;k++){var markerIcon;if(markers[k].markerElement===markerElement){currentInfoWindow=markers[k].infoWindow;}
gMarker=markers[k].markerElement.gmarker;if(gMarker.isActive&&markers[k].markerElement!==markerElement){gMarker.isActive=false;markerIcon=markers[k].markerElement.getAttribute("data-icon")||mapElement.getAttribute("data-icon")
gMarker.setIcon(markerIcon);markers[k].infoWindow.close();}}
currentMarker.isActive=!currentMarker.isActive;if(currentMarker.isActive){if(markerIcon=markerElement.getAttribute("data-icon-active")||mapElement.getAttribute("data-icon-active")){currentMarker.setIcon(markerIcon);}
currentInfoWindow.open(map,marker);}else{if(markerIcon=markerElement.getAttribute("data-icon")||mapElement.getAttribute("data-icon")){currentMarker.setIcon(markerIcon);}
currentInfoWindow.close();}}).bind(this,markerElement,mapElement))})}}}});}
if(navigator.platform.match(/(Mac)/i)){$html.addClass("mac-os");}
if(isIE){if(isIE===12)$html.addClass("ie-edge");if(isIE===11)$html.addClass("ie-11");if(isIE<10)$html.addClass("lt-ie-10");if(isIE<11)$html.addClass("ie-10");}
if(plugins.bootstrapModal.length){for(var i=0;i<plugins.bootstrapModal.length;i++){var modalItem=$(plugins.bootstrapModal[i]);modalItem.on('hidden.bs.modal',$.proxy(function(){var activeModal=$(this),rdVideoInside=activeModal.find('video'),youTubeVideoInside=activeModal.find('iframe');if(rdVideoInside.length){rdVideoInside[0].pause();}
if(youTubeVideoInside.length){var videoUrl=youTubeVideoInside.attr('src');youTubeVideoInside.attr('src','').attr('src',videoUrl);}},modalItem))}}
if(plugins.bootstrapTabs.length){for(var i=0;i<plugins.bootstrapTabs.length;i++){var bootstrapTab=$(plugins.bootstrapTabs[i]);if(bootstrapTab.find('.slick-slider').length){bootstrapTab.find('.tabs-custom-list > li > a').on('click',$.proxy(function(){var $this=$(this);var setTimeOutTime=isNoviBuilder?1500:300;setTimeout(function(){$this.find('.tab-content .tab-pane.active .slick-slider').slick('setPosition');},setTimeOutTime);},bootstrapTab));}
plugins.bootstrapTabs[i].querySelectorAll('.nav li a').forEach(function(tab,index){if(index===0){tab.parentElement.classList.remove('active');$(tab).tab('show');}
tab.addEventListener('click',function(event){event.preventDefault();$(this).tab('show');});});}}
if(plugins.copyrightYear.length){plugins.copyrightYear.text(initialDate.getFullYear());}
if(plugins.maps.length){lazyInit(plugins.maps,initMaps);}
if(plugins.radio.length){for(var i=0;i<plugins.radio.length;i++){$(plugins.radio[i]).addClass("radio-custom").after("<span class='radio-custom-dummy'></span>")}}
if(isDesktop&&!isNoviBuilder){$().UItoTop({easingType:'easeOutQuad',containerClass:'ui-to-top fa fa-angle-up'});}
if(plugins.rdNavbar.length){var
navbar=plugins.rdNavbar,aliases={'-':0,'-sm-':576,'-md-':768,'-lg-':992,'-xl-':1200,'-xxl-':1600},responsive={};for(var alias in aliases){var link=responsive[aliases[alias]]={};if(navbar.attr('data'+alias+'layout'))link.layout=navbar.attr('data'+alias+'layout');if(navbar.attr('data'+alias+'device-layout'))link.deviceLayout=navbar.attr('data'+alias+'device-layout');if(navbar.attr('data'+alias+'hover-on'))link.focusOnHover=navbar.attr('data'+alias+'hover-on')==='true';if(navbar.attr('data'+alias+'auto-height'))link.autoHeight=navbar.attr('data'+alias+'auto-height')==='true';if(navbar.attr('data'+alias+'stick-up-offset'))link.stickUpOffset=navbar.attr('data'+alias+'stick-up-offset');if(navbar.attr('data'+alias+'stick-up'))link.stickUp=navbar.attr('data'+alias+'stick-up')==='true';if(isNoviBuilder)link.stickUp=false;else if(navbar.attr('data'+alias+'stick-up'))link.stickUp=navbar.attr('data'+alias+'stick-up')==='true';}
plugins.rdNavbar.RDNavbar({anchorNav:!isNoviBuilder,stickUpClone:(plugins.rdNavbar.attr("data-stick-up-clone")&&!isNoviBuilder)?plugins.rdNavbar.attr("data-stick-up-clone")==='true':false,responsive:responsive,callbacks:{onStuck:function(){var navbarSearch=this.$element.find('.rd-search input');if(navbarSearch){navbarSearch.val('').trigger('propertychange');}},onDropdownOver:function(){return!isNoviBuilder;},onUnstuck:function(){if(this.$clone===null)
return;var navbarSearch=this.$clone.find('.rd-search input');if(navbarSearch){navbarSearch.val('').trigger('propertychange');navbarSearch.trigger('blur');}}}});if(plugins.rdNavbar.attr("data-body-class")){document.body.className+=' '+plugins.rdNavbar.attr("data-body-class");}}
if(plugins.search.length||plugins.searchResults){var handler="bat/rd-search.php";var defaultTemplate='<h5 class="search-title"><a target="_top" href="#{href}" class="search-link">#{title}</a></h5>'+
'<p>...#{token}...</p>'+
'<p class="match"><em>Terms matched: #{count} - URL: #{href}</em></p>';var defaultFilter='*.html';if(plugins.search.length){for(var i=0;i<plugins.search.length;i++){var searchItem=$(plugins.search[i]),options={element:searchItem,filter:(searchItem.attr('data-search-filter'))?searchItem.attr('data-search-filter'):defaultFilter,template:(searchItem.attr('data-search-template'))?searchItem.attr('data-search-template'):defaultTemplate,live:(searchItem.attr('data-search-live'))?searchItem.attr('data-search-live'):false,liveCount:(searchItem.attr('data-search-live-count'))?parseInt(searchItem.attr('data-search-live'),10):4,current:0,processed:0,timer:{}};var $toggle=$('.rd-navbar-search-toggle');if($toggle.length){$toggle.on('click',(function(searchItem){return function(){if(!($(this).hasClass('active'))){searchItem.find('input').val('').trigger('propertychange');}}})(searchItem));}
if(options.live){var clearHandler=false;searchItem.find('input').on("input propertychange",$.proxy(function(){this.term=this.element.find('input').val().trim();this.spin=this.element.find('.input-group-addon');clearTimeout(this.timer);if(this.term.length>2){this.timer=setTimeout(liveSearch(this),200);if(clearHandler===false){clearHandler=true;$body.on("click",function(e){if($(e.toElement).parents('.rd-search').length===0){$('#rd-search-results-live').addClass('cleared').html('');}})}}else if(this.term.length===0){$('#'+this.live).addClass('cleared').html('');}},options,this));}
searchItem.submit($.proxy(function(){$('<input />').attr('type','hidden').attr('name',"filter").attr('value',this.filter).appendTo(this.element);return true;},options,this))}}
if(plugins.searchResults.length){var regExp=/\?.*s=([^&]+)\&filter=([^&]+)/g;var match=regExp.exec(location.search);if(match!==null){$.get(handler,{s:decodeURI(match[1]),dataType:"html",filter:match[2],template:defaultTemplate,live:''},function(data){plugins.searchResults.html(data);})}}}
if(plugins.swiper.length){for(var i=0;i<plugins.swiper.length;i++){var s=$(plugins.swiper[i]);var pag=s.find(".swiper-pagination"),next=s.find(".swiper-button-next"),prev=s.find(".swiper-button-prev"),bar=s.find(".swiper-scrollbar"),swiperSlide=s.find(".swiper-slide"),autoplay=false;for(var j=0;j<swiperSlide.length;j++){var $this=$(swiperSlide[j]),url;if(url=$this.attr("data-slide-bg")){$this.css({"background-image":"url("+url+")","background-size":"cover"})}}
swiperSlide.end().find("[data-caption-animate]").addClass("not-animated").end();s.swiper({autoplay:!isNoviBuilder&&$.isNumeric(s.attr('data-autoplay'))?s.attr('data-autoplay'):false,direction:s.attr('data-direction')?s.attr('data-direction'):"horizontal",effect:s.attr('data-slide-effect')?s.attr('data-slide-effect'):"slide",speed:s.attr('data-slide-speed')?s.attr('data-slide-speed'):600,keyboardControl:s.attr('data-keyboard')==="true",mousewheelControl:s.attr('data-mousewheel')==="true",mousewheelReleaseOnEdges:s.attr('data-mousewheel-release')==="true",nextButton:next.length?next.get(0):null,prevButton:prev.length?prev.get(0):null,pagination:pag.length?pag.get(0):null,paginationClickable:pag.length?pag.attr("data-clickable")!=="false":false,paginationBulletRender:pag.length?pag.attr("data-index-bullet")==="true"?function(swiper,index,className){return '<span class="'+className+'">'+(index+1)+'</span>';}:null:null,scrollbar:bar.length?bar.get(0):null,scrollbarDraggable:bar.length?bar.attr("data-draggable")!=="false":true,scrollbarHide:bar.length?bar.attr("data-draggable")==="false":false,loop:isNoviBuilder?false:s.attr('data-loop')!=="false",simulateTouch:s.attr('data-simulate-touch')&&!isNoviBuilder?s.attr('data-simulate-touch')==="true":false,onTransitionStart:function(swiper){toggleSwiperInnerVideos(swiper);},onTransitionEnd:function(swiper){toggleSwiperCaptionAnimation(swiper);},onInit:function(swiper){toggleSwiperInnerVideos(swiper);toggleSwiperCaptionAnimation(swiper);initLightGalleryItem(s.find('[data-lightgallery="item"]'),'lightGallery-in-carousel');}});}}
if(plugins.owl.length){for(var i=0;i<plugins.owl.length;i++){var carousel=$(plugins.owl[i]);plugins.owl[i].owl=carousel;initOwlCarousel(carousel);}}
if($html.hasClass("wow-animation")&&plugins.wow.length&&!isNoviBuilder&&isDesktop){new WOW().init();}
if(plugins.rdInputLabel.length){plugins.rdInputLabel.RDInputLabel();}
if(plugins.regula.length){attachFormValidator(plugins.regula);}
if(plugins.rdMailForm.length){var i,j,k,msg={'MF000':'Successfully sent!','MF001':'Recipients are not set!','MF002':'Form will not work locally!','MF003':'Please, define email field in your form!','MF004':'Please, define type of your form!','MF254':'Something went wrong with PHPMailer!','MF255':'Aw, snap! Something went wrong.'};for(i=0;i<plugins.rdMailForm.length;i++){var $form=$(plugins.rdMailForm[i]),formHasCaptcha=false;$form.attr('novalidate','novalidate').ajaxForm({data:{"form-type":$form.attr("data-form-type")||"contact","counter":i},beforeSubmit:function(arr,$form,options){if(isNoviBuilder)
return;var form=$(plugins.rdMailForm[this.extraData.counter]),inputs=form.find("[data-constraints]"),output=$("#"+form.attr("data-form-output")),captcha=form.find('.recaptcha'),captchaFlag=true;output.removeClass("active error success");if(isValidated(inputs,captcha)){if(captcha.length){var captchaToken=captcha.find('.g-recaptcha-response').val(),captchaMsg={'CPT001':'Please, setup you "site key" and "secret key" of reCaptcha','CPT002':'Something wrong with google reCaptcha'};formHasCaptcha=true;$.ajax({method:"POST",url:"bat/reCaptcha.php",data:{'g-recaptcha-response':captchaToken},async:false}).done(function(responceCode){if(responceCode!=='CPT000'){if(output.hasClass("snackbars")){output.html('<p><span class="icon text-middle mdi mdi-check icon-xxs"></span><span>'+captchaMsg[responceCode]+'</span></p>')
setTimeout(function(){output.removeClass("active");},3500);captchaFlag=false;}else{output.html(captchaMsg[responceCode]);}
output.addClass("active");}});}
if(!captchaFlag){return false;}
form.addClass('form-in-process');if(output.hasClass("snackbars")){output.html('<p><span class="icon text-middle fa fa-circle-o-notch fa-spin icon-xxs"></span><span>Sending</span></p>');output.addClass("active");}}else{return false;}},error:function(result){if(isNoviBuilder)
return;var output=$("#"+$(plugins.rdMailForm[this.extraData.counter]).attr("data-form-output")),form=$(plugins.rdMailForm[this.extraData.counter]);output.text(msg[result]);form.removeClass('form-in-process');if(formHasCaptcha){grecaptcha.reset();}},success:function(result){if(isNoviBuilder)
return;var form=$(plugins.rdMailForm[this.extraData.counter]),output=$("#"+form.attr("data-form-output")),select=form.find('select');form.addClass('success').removeClass('form-in-process');if(formHasCaptcha){grecaptcha.reset();}
result=result.length===5?result:'MF255';output.text(msg[result]);if(result==="MF000"){if(output.hasClass("snackbars")){output.html('<p><span class="icon text-middle mdi mdi-check icon-xxs"></span><span>'+msg[result]+'</span></p>');}else{output.addClass("active success");}}else{if(output.hasClass("snackbars")){output.html(' <p class="snackbars-left"><span class="icon icon-xxs mdi mdi-alert-outline text-middle"></span><span>'+msg[result]+'</span></p>');}else{output.addClass("active error");}}
form.clearForm();if(select.length){select.select2("val","");}
form.find('input, textarea').trigger('blur');setTimeout(function(){output.removeClass("active error success");form.removeClass('success');},3500);}});}}
if(plugins.lightGallery.length){for(var i=0;i<plugins.lightGallery.length;i++){initLightGallery(plugins.lightGallery[i]);}}
if(plugins.lightGalleryItem.length){var notCarouselItems=[];for(var z=0;z<plugins.lightGalleryItem.length;z++){if(!$(plugins.lightGalleryItem[z]).parents('.owl-carousel').length&&!$(plugins.lightGalleryItem[z]).parents('.swiper-slider').length&&!$(plugins.lightGalleryItem[z]).parents('.slick-slider').length){notCarouselItems.push(plugins.lightGalleryItem[z]);}}
plugins.lightGalleryItem=notCarouselItems;for(var i=0;i<plugins.lightGalleryItem.length;i++){initLightGalleryItem(plugins.lightGalleryItem[i]);}}
if(plugins.lightDynamicGalleryItem.length){for(var i=0;i<plugins.lightDynamicGalleryItem.length;i++){initDynamicLightGallery(plugins.lightDynamicGalleryItem[i]);}}
if(plugins.customToggle.length){for(var i=0;i<plugins.customToggle.length;i++){var $this=$(plugins.customToggle[i]);$this.on('click',$.proxy(function(event){event.preventDefault();var $ctx=$(this);$($ctx.attr('data-custom-toggle')).add(this).toggleClass('active');},$this));if($this.attr("data-custom-toggle-hide-on-blur")==="true"){$body.on("click",$this,function(e){if(e.target!==e.data[0]&&$(e.data.attr('data-custom-toggle')).find($(e.target)).length&&e.data.find($(e.target)).length===0){$(e.data.attr('data-custom-toggle')).add(e.data[0]).removeClass('active');}})}
if($this.attr("data-custom-toggle-disable-on-blur")==="true"){$body.on("click",$this,function(e){if(e.target!==e.data[0]&&$(e.data.attr('data-custom-toggle')).find($(e.target)).length===0&&e.data.find($(e.target)).length===0){$(e.data.attr('data-custom-toggle')).add(e.data[0]).removeClass('active');}})}}}
if(plugins.circleProgress.length){var i;for(i=0;i<plugins.circleProgress.length;i++){;(function(){var proto=$.circleProgress.defaults,originalDrawEmptyArc=proto.drawEmptyArc;proto.emptyThickness=5;proto.drawEmptyArc=function(v){var oldGetThickness=this.getThickness,oldThickness=this.getThickness(),emptyThickness=this.emptyThickness||_oldThickness.call(this),oldRadius=this.radius,delta=(oldThickness-emptyThickness)/2;this.getThickness=function(){return emptyThickness;};this.radius=oldRadius-delta;this.ctx.save();this.ctx.translate(delta,delta);originalDrawEmptyArc.call(this,v);this.ctx.restore();this.getThickness=oldGetThickness;this.radius=oldRadius;};})();var circleProgressItem=$(plugins.circleProgress[i]);$document.on("scroll",$.proxy(function(){var $this=$(this);if(!$this.hasClass('animated')&&isScrolledIntoView($this)){var arrayGradients=$this.attr('data-gradient').split(",");$this.circleProgress({value:$this.attr('data-value'),size:$this.attr('data-size')?$this.attr('data-size'):175,fill:{gradient:arrayGradients,gradientAngle:Math.PI/4},startAngle:-Math.PI/4*2,emptyFill:$this.attr('data-empty-fill')?$this.attr('data-empty-fill'):"rgb(245,245,245)",thickness:$this.attr('data-thickness')?parseInt($this.attr('data-thickness')):10,emptyThickness:1,}).on('circle-animation-progress',function(event,progress,stepValue){$(this).find('span').text(String(stepValue.toFixed(2)).replace('0.','').replace('1.','1'));});$this.addClass('animated');}},circleProgressItem)).trigger("scroll");}}
if(plugins.slick.length){for(var i=0;i<plugins.slick.length;i++){var $slickItem=$(plugins.slick[i]);$slickItem.on('init',function(slick){initLightGallery($('[data-lightgallery="group-slick"]'),'lightGallery-in-carousel');initLightGallery($('[data-lightgallery="item-slick"]'),'lightGallery-in-carousel');});$slickItem.slick({slidesToScroll:parseInt($slickItem.attr('data-slide-to-scroll'),10)||1,asNavFor:$slickItem.attr('data-for')||false,dots:$slickItem.attr("data-dots")==="true",infinite:isNoviBuilder?false:$slickItem.attr("data-loop")==="true",focusOnSelect:true,arrows:$slickItem.attr("data-arrows")==="true",swipe:$slickItem.attr("data-swipe")==="true",autoplay:$slickItem.attr("data-autoplay")==="true",centerMode:$slickItem.attr("data-center-mode")==="true",centerPadding:$slickItem.attr("data-center-padding")?$slickItem.attr("data-center-padding"):'0.50',mobileFirst:true,nextArrow:'<button type="button" class="slick-next"></button>',prevArrow:'<button type="button" class="slick-prev"></button>',responsive:[{breakpoint:0,settings:{slidesToShow:parseInt($slickItem.attr('data-items'),10)||1,vertical:$slickItem.attr('data-vertical')==='true'||false}},{breakpoint:575,settings:{slidesToShow:parseInt($slickItem.attr('data-sm-items'),10)||1,vertical:$slickItem.attr('data-sm-vertical')==='true'||false}},{breakpoint:767,settings:{slidesToShow:parseInt($slickItem.attr('data-md-items'),10)||1,vertical:$slickItem.attr('data-md-vertical')==='true'||false}},{breakpoint:991,settings:{slidesToShow:parseInt($slickItem.attr('data-lg-items'),10)||1,vertical:$slickItem.attr('data-lg-vertical')==='true'||false}},{breakpoint:1199,settings:{slidesToShow:parseInt($slickItem.attr('data-xl-items'),10)||1,vertical:$slickItem.attr('data-xl-vertical')==='true'||false}}]}).on('afterChange',function(event,slick,currentSlide,nextSlide){var $this=$(this),childCarousel=$this.attr('data-child');if(childCarousel){$(childCarousel+' .slick-slide').removeClass('slick-current');$(childCarousel+' .slick-slide').eq(currentSlide).addClass('slick-current');}});}}
if(plugins.countDown.length){for(var i=0;i<plugins.countDown.length;i++){var $countDownItem=$(plugins.countDown[i]),settings={format:$countDownItem.attr('data-format'),layout:$countDownItem.attr('data-layout')};if(livedemo){var d=new Date();d.setDate(d.getDate()+42);settings[$countDownItem.attr('data-type')]=d;}else{settings[$countDownItem.attr('data-type')]=new Date($countDownItem.attr('data-time'));}
$countDownItem.countdown(settings);}}
if(plugins.rdAudioPlayer.length&&!isNoviBuilder){var i;for(i=0;i<plugins.rdAudioPlayer.length;i++){$(plugins.rdAudioPlayer[i]).RDAudio();}}
if(plugins.calendar.length){var i;for(i=0;i<plugins.calendar.length;i++){var calendarItem=$(plugins.calendar[i]);calendarItem.rdCalendar({days:calendarItem.attr("data-days")?calendarItem.attr("data-days").split(/\s?,\s?/i):['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],month:calendarItem.attr("data-months")?calendarItem.attr("data-months").split(/\s?,\s?/i):['January','February','March','April','May','June','July','August','September','October','November','December']});}}
if(plugins.bookingCalendar.length){var i;for(i=0;i<plugins.bookingCalendar.length;i++){var calendarItem=$(plugins.bookingCalendar[i]);calendarItem.rdCalendar({days:calendarItem.attr("data-days")?calendarItem.attr("data-days").split(/\s?,\s?/i):['S','M','T','W','T','F','S'],month:calendarItem.attr("data-months")?calendarItem.attr("data-months").split(/\s?,\s?/i):['January','February','March','April','May','June','July','August','September','October','November','December']});var temp=$('.rdc-table_has-events');for(i=0;i<temp.length;i++){var $this=$(temp[i]);$this.on("click",i,function(event){event.preventDefault();event.stopPropagation();$(this).toggleClass("opened");var tableEvents=$('.rdc-table_events'),ch=tableEvents.outerHeight(),currentEvent=$(this).children('.rdc-table_events'),eventCell=$('#calendarEvent'+event.data),animationDuration=250;if($(this).hasClass("opened")){$(this).parent().after("<tr id='calendarEvent"+event.data+"' style='height: 0'><td colspan='7'></td></tr>");currentEvent.clone().appendTo($('#calendarEvent'+event.data+' td'));$('#calendarEvent'+event.data+' .rdc-table_events').css("height","0");$('#calendarEvent'+event.data+' .rdc-table_events').animate({height:ch+"px"},animationDuration);}else{$('#calendarEvent'+event.data+' .rdc-table_events').animate({height:"0"},animationDuration);setTimeout(function(){eventCell.remove();},animationDuration);}});};$(window).on('resize',function(){if($('.rdc-table_has-events').hasClass('active')){var tableEvents=$('.rdc-table_events'),ch=tableEvents.outerHeight(),tableEventCounter=$('.rdc-table_events-count');tableEventCounter.css({height:ch+'px'});}});$('input[type="radio"]').on("click",function(){if($(this).attr("value")=="register"){$(".register-form").hide();$(".login-form").fadeIn('slow');}
if($(this).attr("value")=="login"){$(".register-form").fadeIn('slow');$(".login-form").hide();}});$('.rdc-next, .rdc-prev').on("click",function(){var temp=$('.rdc-table_has-events');for(i=0;i<temp.length;i++){var $this=$(temp[i]);$this.on("click",i,function(event){event.preventDefault();event.stopPropagation();$(this).toggleClass("opened");var tableEvents=$('.rdc-table_events'),ch=tableEvents.outerHeight(),currentEvent=$(this).children('.rdc-table_events'),eventCell=$('#calendarEvent'+event.data),animationDuration=250;if($(this).hasClass("opened")){$(this).parent().after("<tr id='calendarEvent"+event.data+"' style='height: 0'><td colspan='7'></td></tr>");currentEvent.clone().appendTo($('#calendarEvent'+event.data+' td'));$('#calendarEvent'+event.data+' .rdc-table_events').css("height","0");$('#calendarEvent'+event.data+' .rdc-table_events').animate({height:ch+"px"},animationDuration);}else{$('#calendarEvent'+event.data+' .rdc-table_events').animate({height:"0"},animationDuration);setTimeout(function(){eventCell.remove();},animationDuration);}});};$(window).on('resize',function(){if($('.rdc-table_has-events').hasClass('active')){var tableEvents=$('.rdc-table_events'),ch=tableEvents.outerHeight(),tableEventCounter=$('.rdc-table_events-count');tableEventCounter.css({height:ch+'px'});}});$('input[type="radio"]').on("click",function(){if($(this).attr("value")=="login"){$(".register-form").hide();$(".login-form").fadeIn('slow');}
if($(this).attr("value")=="register"){$(".register-form").fadeIn('slow');$(".login-form").hide();}});});}}});}());